string object # object id
geometry_msgs/PoseStamped[] poses
bool cartesian_path
uint16 operation
uint16 drill_duration # 0 means don't drill, just touch

uint16 MOVE_THROUGH_POSES=100 #
uint16 MOVE_THROUGH_TRAJECTORY=101 #
uint16 TOUCH_POSES=102

---
uint16 result
uint16 SUCCESS=0
uint16 FAILURE=1 # todo indicate which operation failed?
uint16 BUSY=2 # hand already holds object
uint16 BAD_REQUEST=4
string message
---
uint16 attempt