#!/usr/bin/env python

import rospy
from art_sound import ArtSound

if __name__ == '__main__':
    rospy.init_node('art_sound', log_level=rospy.INFO)

    try:
        ArtSound()
        rospy.spin()
    except rospy.ROSInterruptException:
        pass
