from base import GuiInstruction
from drill_points import DrillPointsLearn, DrillPointsRun, DrillPointsVis
from get_ready import GetReadyLearn, GetReadyRun
from pick_from_feeder import PickFromFeederLearn, PickFromFeederRun, PickFromFeederVis
from pick_from_polygon import PickFromPolygonLearn, PickFromPolygonRun, PickFromPolygonVis
from place_to_grid import PlaceToGridLearn, PlaceToGridRun, PlaceToGridVis
from place_to_pose import PlaceToPoseLearn, PlaceToPoseRun, PlaceToPoseVis
from visual_inspection import VisualInspectionLearn, VisualInspectionRun
from wait_for_user import WaitForUserLearn, WaitForUserRun
from wait_until_user_finishes import WaitUntilUserFinishesLearn, WaitUntilUserFinishesRun
from place_to_container import PlaceToContainerLearn, PlaceToContainerRun
