uint16 INFO=0
uint16 WARN=1
uint16 ERROR=2
uint16 YES_NO_QUESTION=3 # TODO

string message
uint16 type

# 0 means that user should ack the message (close it)
duration duration

# TODO option to specify that yes/no answer is needed?
# TODO option to specify position?
---
string request_id # TODO uuid -> for YES_NO_QUESTION (result will be published on topic)
