#!/usr/bin/env python

import rospy
from art_led import ArtLed

if __name__ == '__main__':
    rospy.init_node('art_led', log_level=rospy.INFO)

    try:
        ArtLed()
        rospy.spin()
    except rospy.ROSInterruptException:
        pass